lang = 0;

translation = [
//JPtrans JP
[  0,"Class","クラス","",""],
[  1,"Lv","Lv","",""],
[  2,"CO SP","CO SP","",""],
[  3,"Used SP","使用済みのSP","",""],
[  4,"Total SP","SPの総計","",""],
[  5,"Hunter","ハンター","",""],
[  6,"Ranger","レンジャー","",""],
[  7,"Force","フォース","",""],
[  8,"Fighter","ファイター","",""],
[  9,"Gunner","ガンナー","",""],
[ 10,"Techer","テクター","",""],
[ 11,"Braver","ブレイバー","",""],
[ 12,"Bouncer","バウンサー","",""],
[ 13,"Class Information","クラス情報","",""],
[ 14,"Options","オプション","",""],
[ 15,"Parameter Information","パラメーター情報","",""],
[ 16,"Skill Tree","スキルツリー","",""],
[ 17,"Base Parameter","ベースパラメーター","",""],
[ 18,"Mag Support Level","マグの支援レベル","",""],
[ 19,"Include","Include","",""],
[ 20,"HP","HP","",""],
[ 21,"PP","PP","",""],
[ 22,"S-ATK","打撃力","",""],
[ 23,"R-ATK","射撃力","",""],
[ 24,"T-ATK","法撃力","",""],
[ 25,"S-DEF","打撃防御","",""],
[ 26,"R-DEF","射撃防御","",""],
[ 27,"T-DEF","法撃防御","",""],
[ 28,"APT","技量","",""],
[ 29,"Race","種族","",""],
[ 30,"♂ Human","♂ ヒューマン","",""],
[ 31,"♀ Human","♀ ヒューマン","",""],
[ 32,"♂ Newman","♂ ニューマン","",""],
[ 33,"♀ Newman","♀ ニューマン","",""],
[ 34,"♂ CAST","♂ キャスト","",""],
[ 35,"♀ CAST","♀ キャスト","",""],
[ 36,"♂ Dewman","♂ デューマン","",""],
[ 37,"♀ Dewman","♀ デューマン","",""],
[ 38,"Language (Game Version)","言語 (ゲームバージョン)","",""],
[ 39,"English (jPSO2)","English (jPSO2)","",""],
[ 40,"日本語 (jPSO2)","日本語 (jPSO2)","",""],
[ 41,"English (iPSO2)","English (iPSO2)","",""],
[ 42,"English (seaPSO2)","English (seaPSO2)","",""],
[ 43,"","","",""],
[ 44,"","","",""],
[ 45,"Show Descriptions","","",""],
[ 46,"Level Details","","",""],
[ 47,"Additional Information","","",""],
[ 48,"Share","共有","",""],
[ 49,"URL","URL","",""],
[ 50,"Text","テキスト","",""],
[ 51,"Save","セーブ","",""],
[ 52,"Load","ロード","",""],
[ 53,"Share URL","","",""],
[ 54,"This is the URL to your skill tree:","","",""],
[ 55,"Share Text","","",""],
[ 56,"This is your skill tree in text form:","","",""],
[ 57,"Load","ロード","",""],
[ 58,"Skilltree loaded from URL.","URLからロードします。","",""],
[ 59,"Close","クローズ","",""],
[ 60,"Slot","スロット","",""],
[ 61,"Empty","なし","",""],
[ 62,"Save","セーブ","",""],
[ 63,"Saved to ","にセーブしました。","",""],
[ 64,"Load","ロード","",""],
[ 65,"Skilltree loaded from Cookie.","クッキーからロードします。","",""],
[ 66,"Name","名前","",""]
]

skillnametrans = [
[  0,"HP Up 1","HPアップ1","",""],
[  1,"HP Up 2","HPアップ2","",""],
[  2,"HP Up 3","HPアップ3","",""],
[  3,"Striking Up 1","打撃アップ1","",""],
[  4,"Striking Up 2","打撃アップ2","",""],
[  5,"Striking Up 3","打撃アップ3","",""],
[  6,"Striking Defence Up 1","打撃防御アップ1","",""],
[  7,"Aptitude Up 1","技量アップ1","",""],
[  8,"HP Up 1","HPアップ1","",""],
[  9,"HP Up 2","HPアップ2","",""],
[ 10,"Striking Up 1","打撃アップ1","",""],
[ 11,"Striking Up 2","打撃アップ2","",""],
[ 12,"Striking Up 3","打撃アップ3","",""],
[ 13,"Aptitude Up 1","技量アップ1","",""],
[ 14,"Aptitude Up 1","技量アップ1","",""],
[ 15,"Aptitude Up 2","技量アップ2","",""],
[ 16,"Aptitude Up 3","技量アップ3","",""],
[ 17,"Shooting Up 1","射撃アップ1","",""],
[ 18,"Shooting Up 2","射撃アップ2","",""],
[ 19,"Shooting Defence Up 1","射撃防御アップ1","",""],
[ 20,"Shooting Up 1","射撃アップ1","",""],
[ 21,"Shooting Up 2","射撃アップ2","",""],
[ 22,"Shooting Up 3","射撃アップ3","",""],
[ 23,"Aptitude Up 1","技量アップ1","",""],
[ 24,"Aptitude Up 2","技量アップ2","",""],
[ 25,"HP Up 1","HPアップ1","",""],
[ 26,"Shooting Defence Up 1","射撃防御アップ1","",""],
[ 27,"Shooting Defence Up 2","射撃防御アップ2","",""],
[ 28,"Technique Up 1","法撃アップ1","",""],
[ 29,"Technique Up 2","法撃アップ2","",""],
[ 30,"Aptitude Up 1","技量アップ1","",""],
[ 31,"PP Up 1","PPアップ1","",""],
[ 32,"PP Up 2","PPアップ2","",""],
[ 33,"Technique Defence Up 1","法撃防御アップ1","",""],
[ 34,"HP Up 1","HPアップ1","",""],
[ 35,"Technique Up 1","法撃アップ1","",""],
[ 36,"Technique Up 2","法撃アップ2","",""],
[ 37,"Striking Up 1","打撃アップ1","",""],
[ 38,"Aptitude Up 1","技量アップ1","",""],
[ 39,"PP Up 1","PPアップ1","",""],
[ 40,"PP Up 2","PPアップ2","",""],
[ 41,"Aptitude Up 1","技量アップ1","",""],
[ 42,"Aptitude Up 2","技量アップ2","",""],
[ 43,"Striking Up 1","打撃アップ1","",""],
[ 44,"Shooting Up 1","射撃アップ1","",""],
[ 45,"Sword Gear","ソードギア","",""],
[ 46,"Partisan Gear","パルチザンギア","",""],
[ 47,"Wired Lance Gear","ワイヤードランスギア","",""],
[ 48,"Knuckle Gear","ナックルギア","",""],
[ 49,"Double Saber Gear","ダブルセイバーギア","",""],
[ 50,"Twin Dagger Gear","ツインダガーギア","",""],
[ 51,"Twin Machine Gun Gear","ツインマシンガンギア","",""],
[ 52,"Wand Gear","ウォンドギア","",""],
[ 53,"Katana Gear","カタナギア","",""],
[ 54,"","","",""],
[ 55,"","","",""],
[ 56,"","","",""],
[ 57,"","","",""],
[ 58,"","","",""],
[ 59,"","","",""],
[ 60,"Step","ステップ","",""],
[ 61,"Step Advance","ステップアドバンス","",""],
[ 62,"Step Attack","ステップアタック","",""],
[ 63,"Just Reversal","ジャストリバーサル","",""],
[ 64,"Dive Roll","ダイブロール","",""],
[ 65,"Dive Roll Advance","ダイブロールアドバンス","",""],
[ 66,"Just Reversal","ジャストリバーサル","",""],
[ 67,"Mirage Escape","ミラージュエスケープ","",""],
[ 68,"Just Reversal","ジャストリバーサル","",""],
[ 69,"","","",""],
[ 70,"Guard","ガード","",""],
[ 71,"Just Guard","ジャストガード","",""],
[ 72,"Just Counter","ジャストカウンター","",""],
[ 73,"Fury Stance","フューリースタンス","",""],
[ 74,"Fury Critical","フューリークリティカル","",""],
[ 75,"Guard Stance","ガードスタンス","",""],
[ 76,"Guard Stance Up 1","ガードスタンスアップ1","",""],
[ 77,"War Cry","ウォークライ","",""],
[ 78,"Automate Halfline","オートメイトハーフライン","",""],
[ 79,"JA Bonus 1","JAボーナス1","",""],
[ 80,"JA Bonus 2","JAボーナス2","",""],
[ 81,"Brave Stance","ブレイブスタンス","",""],
[ 82,"Brave Critical","ブレイブクリティカル","",""],
[ 83,"Brave S Up 1","ブレイブSアップ1","",""],
[ 84,"Wise Stance","ワイズスタンス","",""],
[ 85,"Wise Critical","ワイズクリティカル","",""],
[ 86,"Wise Stance Up 1","ワイズスタンスアップ1","",""],
[ 87,"Weak Hit Advance 1","ウィークヒットアドバンス1","",""],
[ 88,"Weak Hit Advance 2","ウィークヒットアドバンス2","",""],
[ 89,"Standing Snipe 1","スタンディングスナイプ1","",""],
[ 90,"Tool Mastery","ツールマスタリー","",""],
[ 91,"Upper Trap","アッパートラップ","",""],
[ 92,"Upper T Custom","アッパーTカスタム","",""],
[ 93,"Poison Trap","ポイズントラップ","",""],
[ 94,"Poison T Custom","ポイズンTカスタム","",""],
[ 95,"Stun Grenade","スタングレネード","",""],
[ 96,"Weak Bullet","ウィークバレット","",""],
[ 97,"Bind Bullet","バインドバレット","",""],
[ 98,"Panic Shot","パニックショット","",""],
[ 99,"Jellen Shot","ジェルンショット","",""],
[100,"Fury S Up 1","フューリーSアップ1","",""],
[101,"Fury S Up 2","フューリーSアップ2","",""],
[102,"Iron Will","アイアンウィル","",""],
[103,"Flash Guard 1","フラッシュガード1","",""],
[104,"Guard Stance Poison","ガードスタンスポイズン","",""],
[105,"Guard Stance Burn","ガードスタンスバーン","",""],
[106,"Flash Tech Guard","フラッシュテックガード","",""],
[107,"Flash Guard 2","フラッシュガード2","",""],
[108,"Chase Advance","チェイスアドバンス","",""],
[109,"Chase Bind","チェイスバインド","",""],
[110,"Deadline Slayer","デッドラインスレイヤー","",""],
[111,"Halfline Slayer","ハーフラインスレイヤー","",""],
[112,"Standing Snipe 2","スタンディングスナイプ2","",""],
[113,"Trap Search","トラップサーチ","",""],
[114,"Mirage Shot","ミラージュショット","",""],
[115,"Zero Range Advance 1","ゼロレンジアドバンス1","",""],
[116,"Zero Range Advance 2","ゼロレンジアドバンス2","",""],
[117,"Attack PP Restorate","アタックPPリストレイト","",""],
[118,"Showtime","ショウタイム","",""],
[119,"Chain Trigger","チェイントリガー","",""],
[120,"Chain Finish","チェインフィニッシュ","",""],
[121,"Aerial Advance","エアリアルアドバンス","",""],
[122,"Automate Deadline","オートメイトデッドライン","",""],
[123,"Flame Mastery 1","フレイムマスタリー1","",""],
[124,"Flame Mastery 2","フレイムマスタリー2","",""],
[125,"Ice Mastery 1","アイスマスタリー1","",""],
[126,"Ice Mastery 2","アイスマスタリー2","",""],
[127,"Bolt Mastery 1","ボルトマスタリー1","",""],
[128,"Bolt Mastery 2","ボルトマスタリー2","",""],
[129,"Burn Boost","バーンブースト","",""],
[130,"Freeze Boost","フリーズブースト","",""],
[131,"Shock Boost","ショックブースト","",""],
[132,"Flame Tech S Charge","フレイムテックSチャージ","",""],
[133,"Charge PP Revival","チャージPPリバイバル","",""],
[134,"Tech Charge Advance 1","テックチャージアドバンス1","",""],
[135,"Tech Charge Advance 2","テックチャージアドバンス2","",""],
[136,"Freeze Ignition","フリーズイグニッション","",""],
[137,"Photon Flare","フォトンフレア","",""],
[138,"Photon Flare Advance","フォトンフレアアドバンス","",""],
[139,"Bolt Tech PP Save","ボルトテックPPセイブ","",""],
[140,"Normal Tech Advance","ノーマルテックアドバンス","",""],
[141,"Tech JA Advance","テックJAアドバンス","",""],
[142,"Shifta Advance","シフタアドバンス","",""],
[143,"Shifta Critical","シフタクリティカル","",""],
[144,"Deband Advance","デバンドアドバンス","",""],
[145,"Deband Cut","デバンドカット","",""],
[146,"Wind Mastery 1","ウィンドマスタリー1","",""],
[147,"Wind Mastery 2","ウィンドマスタリー2","",""],
[148,"Light Mastery 1","ライトマスタリー1","",""],
[149,"Light Mastery 2","ライトマスタリー2","",""],
[150,"Dark Mastery 1","ダークマスタリー1","",""],
[151,"Dark Mastery 2","ダークマスタリー2","",""],
[152,"Mirage Boost","ミラージュブースト","",""],
[153,"Panic Boost","パニックブースト","",""],
[154,"Poison Boost","ポイズンブースト","",""],
[155,"Territory Burst","テリトリーバースト","",""],
[156,"Resta Advance","レスタアドバンス","",""],
[157,"PP Restorate 1","PPリストレイト1","",""],
[158,"Element Weak Hit","エレメントウィークヒット","",""],
[159,"Poison Ignition","ポイズンイグニッション","",""],
[160,"PP Convert","PPコンバート","",""],
[161,"Fury Combo Up","フューリーコンボアップ","",""],
[162,"PP Slayer","PPスレイヤー","",""],
[163,"Killing Bonus","キリングボーナス","",""],
[164,"Perfect Keeper","パーフェクトキーパー","",""],
[165,"Photon Flare After Burst","フォトンフレアアフターバースト","",""],
[166,"Extend Assist","エクステンドアシスト","",""],
[167,"Rare Mastery Hunter","レアマスタリーハンター","",""],
[168,"Rare Mastery Fighter","レアマスタリーファイター","",""],
[169,"Rare Mastery Ranger","レアマスタリーレンジャー","",""],
[170,"Rare Mastery Gunner","レアマスタリーガンナー","",""],
[171,"Rare Mastery Force","レアマスタリーフォース","",""],
[172,"Rare Mastery Techer","レアマスタリーテクター","",""],
[173,"Absorption","アブソプション","",""],
[174,"Massive Hunter","マッシブハンター","",""],
[175,"Adrenaline","アドレナリン","",""],
[176,"Crazy Heart","クレイジーハート","",""],
[177,"Crazy Beat","クレイジービート","",""],
[178,"PP Save Bullet","PPセイブバレット","",""],
[179,"Tactics Trap","タクティクストラップ","",""],
[180,"Power Bullet","パワーバレット","",""],
[181,"S Roll Up","Sロールアップ","",""],
[182,"S Roll JA Bonus","SロールJAボーナス","",""],
[183,"S Roll Arts","Sロールアーツ","",""],
[184,"Showtime Star","ショウタイムスター","",""],
[185,"Photon Flare Boost","フォトンフレアブースト","",""],
[186,"Freeze Keep","フリーズキープ","",""],
[187,"F Ignition Boost","Fイグニッションブースト","",""],
[188,"Wand Reactor","ウォンドリアクター","",""],
[189,"Wand Lovers","ウォンドラバーズ","",""],
[190,"Katana Combat","カタナコンバット","",""],
[191,"Combat JA Bonus","コンバットJAボーナス","",""],
[192,"Combat Finish","コンバットフィニッシュ","",""],
[193,"Rapid Shoot","ラピッドシュート","",""],
[194,"Rapid Shoot Up 1","ラピッドシュートアップ1","",""],
[195,"Rapid Shoot Mastery","ラピッドシュートマスタリー","",""],
[196,"Average Stance","アベレージスタンス","",""],
[197,"Average S Up","アベレージSアップ","",""],
[198,"Average S Critical","アベレージSクリティカル","",""],
[199,"Average S Charge","アベレージSチャージ","",""],
[200,"Weak Stance","ウィークスタンス","",""],
[201,"Weak Stance Up","ウィークスタンスアップ","",""],
[202,"Weak Stance Critical","ウィークスタンスクリティカル","",""],
[203,"Weak Stance Charge","ウィークスタンスチャージ","",""],
[204,"Braver Mag","ブレイバーマグ","",""],
[205,"Rare Mastery Braver","レアマスタリーブレイバー","",""],
[206,"J Reversal Cover","Jリバーサルカバー","",""],
[207,"Snatch Step","スナッチステップ","",""],
[208,"Never Give Up","ネバーギブアップ","",""],
[209,"Pretty Good","プリティグッド","",""],
[210,"Half Line Boost","ハーフラインブースト","",""],
[211,"Chase Advance Plus","チェイスアドバンスプラス","",""],
[212,"Weak Hit Blast Bonus","ウィークヒットブラストボーナス","",""],
[213,"First Hit","ファーストヒット","",""],
[214,"Zero Range Critical","ゼロレンジクリティカル","",""],
[215,"Toughness Time","タフネスタイム","",""],
[216,"Talis Tech Bonus","タリステックボーナス","",""],
[217,"Technique High Up","法撃ハイアップ","",""],
[218,"Super Treatment","スーパートリートメント","",""],
[219,"Territory PP Save","テリトリーPPセイブ","",""],
[220,"Combat Escape","コンバットエスケープ","",""],
[221,"Rapid Shoot Up 2","ラピッドシュートアップ2","",""],
[222,"Hunter Gear Boost","ハンターギアブースト","",""],
[223,"Critical Strike","クリティカルストライク","",""],
[224,"Sharpshooter","シャープシューター","",""],
[225,"High Time","ハイタイム","",""],
[226,"Element Conversion","エレメントコンバージョン","",""],
[227,"Long-Time Assist","ロングタイムアシスト","",""],
[228,"Counter Edge","カウンターエッジ","",""],
[229,"Rapid Shoot Advance","ラピッドシュートアドバンス","",""],
[230,"Healing Guard","ヒーリングガード","",""],
[231,"War Brave","ウォーブレイブ","",""],
[232,"Tech Arts JA Bonus","テックアーツJAボーナス","",""],
[233,"Limit Break","リミットブレイク","",""],
[234,"Gravity Bomb","グラヴィティボム","",""],
[235,"Bullet Keep","バレットキープ","",""],
[236,"Twice Chain","トワイスチェイン","",""],
[237,"Chain F Bonus","チェインFボーナス","",""],
[238,"Charge Escape","チャージエスケープ","",""],
[239,"Shifta Strike","シフタストライク","",""],
[240,"Deband Toughness","デバンドタフネス","",""],
[241,"Attack Advance","アタックアドバンス","",""],
[242,"Charge Shoot","チャージシュート","",""],
[243,"J Reversal PP Gain","JリバーサルPPゲイン","",""],
[244,"Rare Mastery Bouncer","レアマスタリーバウンサー","",""],
[245,"Craft Mastery","クラフトマスタリー","",""],
[246,"Bouncer Mag","バウンサーマグ","",""],
[247,"Jet Boots Gear","ジェットブーツギア","",""],
[248,"Dual Blade Gear","デュアルブレードギア","",""],
[249,"Elemental PP Restorate F","エレメンタルPPリストレイトF","",""],
[250,"Critical Field","クリティカルフィールド","",""],
[251,"Shifta Air Attack Boost","シフタエアアタックブースト","",""],
[252,"Deband PP Restorate","デバンドPPリストレイト","",""],
[253,"Heal Share","ヒールシェア","",""],
[254,"Heal Bonus","ヒールボーナス","",""],
[255,"Rapid Boost","ラピッドブースト","",""],
[256,"Rapid Boost JA Bonus","ラピッドブーストJAボーナス","",""],
[257,"Elemental Burst","エレメンタルバースト","",""],
[258,"Jet Boots Strike","ジェットブーツストライク","",""],
[259,"Photon Blade Fever","フォトンブレードフィーバー","",""],
[260,"Photon Blade Fever Up 1","フォトンブレードフィーバーアップ1","",""],
[261,"Photon Blade Escape","フォトンブレードエスケープ","",""],
[262,"Elemental Stance","エレメンタルスタンス","",""],
[263,"Elemental Stance Up 1","エレメンタルスタンスアップ1","",""],
[264,"Elemental S Critical","エレメンタルSクリティカル","",""],
[265,"Break Stance","ブレイクスタンス","",""],
[266,"Break Stance Up 1","ブレイクスタンスアップ1","",""],
[267,"Break S Critical","ブレイクSクリティカル","",""],
[268,"Aptitude Up 1","技量アップ1","",""],
[269,"Striking Up 1","打撃アップ1","",""],
[270,"Striking Up 2","打撃アップ2","",""],
[271,"Technique Up 1","法撃アップ1","",""],
[272,"Striking Defence Up 1","打撃防御アップ1","",""],
[273,"Technique Defence Up 1","法撃防御アップ1","",""],
[274,"All Guard","オールガード","",""],
[275,"Guard Stance Advance","ガードスタンスアドバンス","",""],
[276,"D Saber Wind Parrying","Dセイバーウィンドパリング","",""],
[277,"T Dagger Spin Move","Tダガースピンムーブ","",""],
[278,"Knuckle Gear Boost","ナックルギアブースト","",""],
[279,"Dive Roll Shoot","ダイブロールシュート","",""],
[280,"Moving Snipe","ムービングスナイプ","",""],
[281,"Dive Roll Shoot","ダイブロールシュート","",""],
[282,"One More Time","ワンモアタイム","",""],
[283,"Rod Keep Bonus","ロッドキープボーナス","",""],
[284,"Reverse Bonus","リバースボーナス","",""],
[285,"Reverser Field","リバーサーフィールド","",""],
[286,"Snatch JA Combo","スナッチJAコンボ","",""],
[287,"Quick Mate","クイックメイト","",""],
[288,"Field Remain","フィールドリメイン","",""],
[289,"Break SD Bonus","ブレイクSDボーナス","",""],
[290,"Just Guard PP Gain","ジャストガードPPゲイン","",""],
[291,"Limit Break Photon Charge","リミットブレイクフォトンチャージ","",""],
[292,"Massive Bullet","マッシブバレット","",""],
[293,"T Machine Gun Mastery","Tマシンガンマスタリー","",""],
[294,"Talis Fast Throw","タリスファストスロー","",""],
[295,"Wide Support","ワイドサポート","",""],
[296,"Counter Bonus","カウンターボーナス","",""],
[297,"Bullet Bow Charge Bonus","バレットボウチャージボーナス","",""],
[298,"Jet Boots Escape","ジェットブーツエスケープ","",""],
[299,"Jet Boots Gear Boost","ジェットブーツギアブースト","",""]
]

skilldesctrans = [
[  0,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[  1,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[  2,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[  3,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[  4,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[  5,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[  6,"Passive<br><br>Increase your S-DEF.","打撃防御力が上昇する","",""],
[  7,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[  8,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[  9,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[ 10,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[ 11,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[ 12,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[ 13,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 14,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 15,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 16,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 17,"Passive<br><br>Increase your R-ATK.","射撃力が上昇する","",""],
[ 18,"Passive<br><br>Increase your R-ATK.","射撃力が上昇する","",""],
[ 19,"Passive<br><br>Increase your R-DEF.","射撃防御力が上昇する","",""],
[ 20,"Passive<br><br>Increase your R-ATK.","射撃力が上昇する","",""],
[ 21,"Passive<br><br>Increase your R-ATK.","射撃力が上昇する","",""],
[ 22,"Passive<br><br>Increase your R-ATK.","射撃力が上昇する","",""],
[ 23,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 24,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 25,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[ 26,"Passive<br><br>Increase your R-DEF.","射撃防御力が上昇する","",""],
[ 27,"Passive<br><br>Increase your R-DEF.","射撃防御力が上昇する","",""],
[ 28,"Passive<br><br>Increase your T-ATK.","法撃力が上昇する","",""],
[ 29,"Passive<br><br>Increase your T-ATK.","法撃力が上昇する","",""],
[ 30,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 31,"Passive<br><br>Increase your maximum PP.","PP最大値が上昇する","",""],
[ 32,"Passive<br><br>Increase your maximum PP.","PP最大値が上昇する","",""],
[ 33,"Passive<br><br>Increase your T-DEF.","法撃防御力が上昇する","",""],
[ 34,"Passive<br><br>Increase your maximum HP.","HP最大値が上昇する","",""],
[ 35,"Passive<br><br>Increase your T-ATK.","法撃力が上昇する","",""],
[ 36,"Passive<br><br>Increase your T-ATK.","法撃力が上昇する","",""],
[ 37,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[ 38,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 39,"Passive<br><br>Increase your maximum PP.","PP最大値が上昇する","",""],
[ 40,"Passive<br><br>Increase your maximum PP.","PP最大値が上昇する","",""],
[ 41,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 42,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[ 43,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[ 44,"Passive<br><br>Increase your R-ATK.","射撃力が上昇する","",""],
[ 45,"Passive<br><br>By filling the Gear Gauge the attack area, number of hits and charge tempo change depending on the PA.","ギアゲージを溜めることで、PAの種類に応じて攻撃範囲、ヒット数、チャージ速度が変化する","",""],
[ 46,"Passive<br><br>PAs consume one Gear Gauge stock to increase their attack area and power.","PA使用時にギアゲージを1つ消費して攻撃範囲を広げ威力が上昇する","",""],
[ 47,"Passive<br><br>Hold PAs consume one Gear Gauge stock to increase their power","ホールドPA使用時にギアゲージを1つ消費して威力が上昇する","",""],
[ 48,"Passive<br><br>Accumulate Gear according to the number of consecutive attacks. Increases attack speed depending on the number of Gears.","連続攻撃の段数に応じて、ギアが溜まり、ギア数に応じて攻撃速度が上昇する","",""],
[ 49,"Passive<br><br>Accumumulate Gear whenever attacks hit and release with weapon action. Damage and area of the razor-sharp wind around you depend on the number of Gears.","攻撃を当てるとギアが溜まり、武器アクションで解放。ギアの段数に応じて、ダメージを与えるかまいたちを周囲にまとう","",""],
[ 50,"Passive<br><br>Accumulates Gear according to the number of jumps. Increases the power of PAs depending on the number of Gears.","ジャンプ回数に応じて、ギアが溜まり、ギア数に応じてPAの威力が上昇する","",""],
[ 51,"Passive<br><br>Accumulate Gear whenever attacks hit. Increases power of attacks.","攻撃を当てるとギアが溜まり、攻撃の威力が上昇する","",""],
[ 52,"Passive<br><br>Accumulate Gear whenever enemies are hit by charged techniques. Basic attacks cause tech explosions.","チャージテクニックをエネミーに当てるとギアが溜まり、通常攻撃で法撃爆発を発生させる","",""],
[ 53,"Passive<br><br>Increases counter attack range and power by filling the Gear Gauge. When a counter is performed with maximum Gear, gain a bonus to your attack power and critical hit rate for a fixed time.","ギアゲージを貯めるとカウンターの攻撃範囲と威力が上昇。最大ギア状態でカウンターを行うと、一定時間攻撃力とクリティカルヒット率にボーナスを得る。","",""],
[ 54,"","","",""],
[ 55,"","","",""],
[ 56,"","","",""],
[ 57,"","","",""],
[ 58,"","","",""],
[ 59,"","","",""],
[ 60,"Active<br><br>Move forward a short distance.","軽快な動作で踏み込み短距離を素早く移動する","",""],
[ 61,"Passive<br><br>Extends the invulnerability during Step.","ステップ中の無敵時間を延長する","",""],
[ 62,"Passive<br><br>Allows you to perform an attack during a Step.","ステップ中の攻撃アクションが可能となる","",""],
[ 63,"Passive<br><br>Press the jump button to quickly recover when knocked down.","吹き飛ばされてダウンしたときにジャンプ操作で素早く起き上がる","",""],
[ 64,"Active<br><br>Move forward a short distance by dive rolling.","飛び込むような挙動で短距離を素早く移動する","",""],
[ 65,"Passive<br><br>Extends the invulnerability during Dive Roll.","ダイブロール中の無敵時間を延長する","",""],
[ 66,"Passive<br><br>Press the jump button to quickly recover when knocked down.","吹き飛ばされてダウンしたときにジャンプ操作で素早く起き上がる","",""],
[ 67,"Active<br><br>Disturb visual information and move a fixed distance while invulnerable.","視覚情報を撹乱し、無敵状態で一定距離を移動する","",""],
[ 68,"Passive<br><br>Press the jump button to quickly recover when knocked down.","吹き飛ばされてダウンしたときにジャンプ操作で素早く起き上がる","",""],
[ 69,"","","",""],
[ 70,"Active<br><br>Hold up your weapon to block enemy attacks.","武器を正面に構えて、エネミーの攻撃を防ぐ","",""],
[ 71,"Passive<br><br>Use Guard right before an attack to reduce the damage taken significantly.","攻撃を受ける直前にガードをすることで、ダメージを無効にする","",""],
[ 72,"Passive<br><br>Turns attacks right after Just Guards into Just Attacks.","ジャストガード成功直後の攻撃がジャストアタックになる","",""],
[ 73,"Active<br><br>Stance which increases striking and ranged damage dealt and striking damage received.","エネミーへの打撃・射撃ダメージを上昇させ、自分への打撃ダメージを上昇させるスタンススキル。リキャスト60秒","",""],
[ 74,"Passive<br><br>Increases your critical hit rate during Fury Stance.","フューリースタンス中のクリティカルヒット率をアップ","",""],
[ 75,"Active<br><br>Stance which reduces striking and ranged damage dealt and striking damage received.","エネミーへの打撃・射撃ダメージを低下させ、自分への打撃ダメージを軽減するスタンススキル。リキャスト60秒","",""],
[ 76,"Passive<br><br>Increases your striking resistance during Guard Stance.","ガードスタンス中の打撃耐性をアップ","",""],
[ 77,"Active<br><br>Attract the attention of enemies.","エネミーの注意を引き付ける","",""],
[ 78,"Passive<br><br>When your HP fall below 50%, automatically use a Mate item on yourself.","HPが50%未満になったとき、自動でメイト系アイテムを使用する","",""],
[ 79,"Passive<br><br>Increases the damage of Just Attacks, but not techniques.","テクニック以外のジャストアタックにダメージボーナスを得る","",""],
[ 80,"Passive<br><br>Increases the damage of Just Attacks, but not techniques.","テクニック以外のジャストアタックにダメージボーナスを得る","",""],
[ 81,"Active<br><br>Stance which increases damage inflicted from the front while decreasing damage inflicted the back.","正面から与えるダメージが増加するスタンススキル。背後から与えるダメージは減少する","",""],
[ 82,"Passive<br><br>Increases your critical hit rate during Brave Stance when attacking from the front.","ブレイブスタンス中、エネミーの前面からダメージを与えたときのクリティカルヒット確率が上昇する","",""],
[ 83,"Passive<br><br>Increases damage during Brave Stance when attacking from the front.","ブレイブスタンス中、エネミーの前面からダメージを与えたときにボーナスを得る","",""],
[ 84,"Active<br><br>Stance which increases damage inflicted from the back while decreasing damage inflicted the front.","背後から与えるダメージが増加するスタンススキル。正面から与えるダメージは減少する","",""],
[ 85,"Passive<br><br>Increases your critical hit rate during Wise Stance when attacking from the back.","ワイズスタンス中、エネミーの背後からダメージを与えたときのクリティカルヒット確率が上昇する","",""],
[ 86,"Passive<br><br>Increases damage during Wise Stance when attacking from the back.","ワイズスタンス中、エネミーの背後からダメージを与えたときにボーナスを得る","",""],
[ 87,"Passive<br><br>Increases your damage against weak spots using shooting attacks.","射撃で弱点部位を攻撃したときのダメージが上昇する","",""],
[ 88,"Passive<br><br>Increases your damage against weak spots using shooting attacks.","射撃で弱点部位を攻撃したときのダメージが上昇する","",""],
[ 89,"Passive<br><br>Increases your damage when standing still using shooting attacks.","静止した状態で射撃したときのダメージが上昇する","",""],
[ 90,"Passive<br><br>Increases the power of Tool skills.","ツール系スキルの威力が増加する","",""],
[ 91,"Active<br><br>Places a trap that launches enemies into the air. Reactivating the skill detonates the trap. Requires 1 Upper Trap.","エネミーを打ち上げるトラップを設置する","",""],
[ 92,"Passive<br><br>Increases the power of Upper Trap.","アッパートラップの威力が上昇する","",""],
[ 93,"Active<br><br>Places a poison trap. Reactivating the skill detonates the trap. Requires 1 Poison Trap.","ポイズントラップを設置する","",""],
[ 94,"Passive<br><br>Increases the probability of inflicting poison status of Poison Trap.","ポイズントラップのポイズン確率が上昇する","",""],
[ 95,"Active<br><br>Throws a hand grenade which inflicts stun status. Requires 1 Stun Grenade.","エネミーをスタン状態にする閃光弾を投擲する","",""],
[ 96,"Active<br><br>Assault rifle exclusive skill. Loads weakening bullets.","アサルトライフル専用スキル。エネミーの防御力を低下させる脆弱化弾を装填する","",""],
[ 97,"Active<br><br>Assault rifle exclusive skill. Loads binding bullets.","アサルトライフル専用スキル バインド効果を与えるバインド弾を装填する","",""],
[ 98,"Active<br><br>Launcher exclusive skill. Loads panic bullets.","ランチャー専用スキル　パニック効果を与えるパニック弾を装填する","",""],
[ 99,"Active<br><br>Launcher exclusive skill. Loads Jellen bullets.","ランチャー専用スキル エネミーの攻撃力を低下させるジェルン弾を装填する","",""],
[100,"Passive<br><br>Increases your striking and shooting damage during Fury Stance.","フューリースタンス中にエネミーへの打撃・射撃ダメージを上昇する","",""],
[101,"Passive<br><br>Increases your striking and shooting damage during Fury Stance.","フューリースタンス中にエネミーへの打撃・射撃ダメージを上昇する","",""],
[102,"Passive<br><br>May survive with 1 HP left when receiving damage that would kill you.","戦闘不能となるダメージを受けたとき、HPが1残ることがある","",""],
[103,"Passive<br><br>Reduces striking and shooting damage taken.","打撃・射撃ダメージを軽減する","",""],
[104,"Passive<br><br>Recover from poison status when activating Guard Stance.","ガードスタンス発動時に状態異常ポイズンを回復する","",""],
[105,"Passive<br><br>Recover from burn status when activating Guard Stance.","ガードスタンス発動時に状態異常バーンを回復する","",""],
[106,"Passive<br><br>Reduces technique damage taken.","法撃ダメージを軽減する","",""],
[107,"Passive<br><br>Reduces striking and shooting damage taken.","打撃・射撃ダメージを軽減する","",""],
[108,"Passive<br><br>Increases your damage against enemies suffering under status abnormalities using striking attacks.","状態異常を受けているエネミーに対して打撃攻撃を行うとダメージボーナスを得る","",""],
[109,"Passive<br><br>Attacking enemies suffering under status abnormalities with striking attacks may cause bind status.","状態異常を受けているエネミーに対して打撃攻撃を行うとバインド状態にすることがある","",""],
[110,"Passive<br><br>Increases S-ATK and R-ATK when HP fall below 25%.","HPが25%以下になったとき、打撃力と射撃力が上昇する","",""],
[111,"Passive<br><br>Increases S-ATK and R-ATK when HP fall below 50%.","HPが50%以下になったとき、打撃力と射撃力が上昇する","",""],
[112,"Passive<br><br>Increases your damage when standing still using shooting attacks.","静止した状態で射撃したときのダメージが上昇する","",""],
[113,"Passive<br><br>Find hidden traps.","隠されたトラップを発見する","",""],
[114,"Active<br><br>Launcher exclusive skill. Loads Mirage bullets.","ランチャー専用スキル ミラージュ効果を与えるミラージュ弾を装填する","",""],
[115,"Passive<br><br>Increases your damage using shooting attacks in close range.","近距離で射撃攻撃をヒットするとダメージが上昇する","",""],
[116,"Passive<br><br>Increases your damage using shooting attacks in close range.","近距離で射撃攻撃をヒットするとダメージが上昇する","",""],
[117,"Passive<br><br>Increases the PP restoration of normal attacks.","通常攻撃をヒットさせたときのPP回復量が増加する","",""],
[118,"Active<br><br>Twin machine gun exclusive skill. Increases your gear gauge fill rate and attracts the enemy's attention.","ツインマシンガン専用スキル 一定時間エネミーの自分に対するヘイト効果を上昇する代わりに、ギアの上昇率を大きく上げる","",""],
[119,"Active<br><br>After activating the skill, your next hit starts a chain counter.","スキル発動後に通常攻撃をヒットさせるとチェインを開始する","",""],
[120,"Passive<br><br>Increases the damage of Chain Finish.","チェインフィニッシュダメージが上昇する","",""],
[121,"Passive<br><br>Increases damage inflicted to enemies midair.","空中にいるエネミーに攻撃をヒットさせたときダメージが上昇する","",""],
[122,"Passive<br><br>When your HP fall below 25%, automatically use a Mate item on yourself.","HPが25%未満になったとき、自動でメイト系アイテムを使用する","",""],
[123,"Passive<br><br>Increases the power of flame techniques.","炎系テクニックの威力が上昇する","",""],
[124,"Passive<br><br>Increases the power of flame techniques.","炎系テクニックの威力が上昇する","",""],
[125,"Passive<br><br>Increases the power of ice techniques.","氷系テクニックの威力が上昇する","",""],
[126,"Passive<br><br>Increases the power of ice techniques.","氷系テクニックの威力が上昇する","",""],
[127,"Passive<br><br>Increases the power of thunder techniques.","雷系テクニックの威力が上昇する","",""],
[128,"Passive<br><br>Increases the power of thunder techniques.","雷系テクニックの威力が上昇する","",""],
[129,"Passive<br><br>Increases the chance of inflicting burn status.","バーン確率が上昇する","",""],
[130,"Passive<br><br>Increases the chance of inflicting freeze status.","フリーズ確率が上昇する","",""],
[131,"Passive<br><br>Increases the chance of inflicting shock status.","ショック確率が上昇する","",""],
[132,"Passive<br><br>Reduces the charge time of flame techniques.","炎系テクニックのチャージ時間を短縮する","",""],
[133,"Passive<br><br>Recovers PP while charging.","テクニックのチャージ中にPPが回復する","",""],
[134,"Passive<br><br>Increases the damage of charged techniques.","チャージテクニックのダメージが上昇する","",""],
[135,"Passive<br><br>Increases the damage of charged techniques.","チャージテクニックのダメージが上昇する","",""],
[136,"Active<br><br>Detonates frozen enemies.","フリーズ状態のエネミーを爆破し、大きなダメージを与える","",""],
[137,"Active<br><br>Increases T-ATK for a short period of time.","一時的に法撃力を上昇させる","",""],
[138,"Passive<br><br>Increases T-ATK when activating Photon Flare.","フォトンフレア発動時に、さらに法撃力が上昇する","",""],
[139,"Passive<br><br>Decreases the PP consumption of thunder techniques.","雷系テクニックのPP消費量が減少する","",""],
[140,"Passive<br><br>Increases the damage of uncharged techniques.","チャージしていないテクニックのダメージが上昇する","",""],
[141,"Passive<br><br>Increases the damage of techniques when performing Just Attacks.","テクニックのジャストアタックにダメージボーナスを得る","",""],
[142,"Passive<br><br>Increases Shifta's effectiveness.","シフタの効果が上昇する","",""],
[143,"Passive<br><br>Increases critical hit rate during Shifta.","シフタ効果中にクリティカルヒット確率が上昇する","",""],
[144,"Passive<br><br>Increases Deband's effectiveness.","デバンドの効果が上昇する","",""],
[145,"Passive<br><br>Reduces a fixed amount of damage during Deband.","デバンド効果中に一定の割合のダメージを軽減する","",""],
[146,"Passive<br><br>Increases the power of wind techniques.","風系テクニックの威力が上昇する","",""],
[147,"Passive<br><br>Increases the power of wind techniques.","風系テクニックの威力が上昇する","",""],
[148,"Passive<br><br>Increases the power of light techniques.","光系テクニックの威力が上昇する","",""],
[149,"Passive<br><br>Increases the power of light techniques.","光系テクニックの威力が上昇する","",""],
[150,"Passive<br><br>Increases the power of dark techniques.","闇系テクニックの威力が上昇する","",""],
[151,"Passive<br><br>Increases the power of dark techniques.","闇系テクニックの威力が上昇する","",""],
[152,"Passive<br><br>Increases the chance of inflicting mirage status.","ミラージュの発生確率が上昇","",""],
[153,"Passive<br><br>Increases the chance of inflicting panic status.","パニックの発生確率が上昇する","",""],
[154,"Passive<br><br>Increases the chance of inflicting poison status.","ポイズンの発生確率が上昇する","",""],
[155,"Passive<br><br>Increases the area of effect of support techiques.","補助テクニックの効果範囲が上昇する","",""],
[156,"Passive<br><br>Increases HP recovered with Resta.","レスタ回復量が上昇する","",""],
[157,"Passive<br><br>Increases your passive PP restoration rate.","PP自動回復量が上昇する","",""],
[158,"Passive<br><br>Increases your damage against your enemy's weak element.","弱点属性へのダメージを上昇する","",""],
[159,"Active<br><br>Detonates poisoned enemies. Enemies within explosion range take damage and have a chance of becoming poisoned.","ポイズン状態のエネミーを爆発する。爆発に巻き込まれたエネミーはダメージを受け、ポイズンとなることがある","",""],
[160,"Active<br><br>Increases your PP restoration rate at the expense of your maximum HP for a short period of time.","一定時間、PP回復量が上昇し、最大HPが減少する。","",""],
[161,"Passive<br><br>While in Fury Stance, receive a damage bonus by continually performing Just Attacks successfully.","フューリースタンス状態のとき、連続でジャストアタックに成功するとダメージボーナスを得る","",""],
[162,"Passive<br><br>Increases S-ATK and R-ATK when PP fall below 50%.","PPが50%以下になったとき、打撃力と射撃力が上昇する","",""],
[163,"Passive<br><br>Gain a chance to recover PP when an enemy in your vicinity is killed.","一定範囲内でエネミーが死亡すると、PPが回復する","",""],
[164,"Passive<br><br>Increases damage dealt against enemies when HP are at 100%.","HPが100%のとき、エネミーへのダメージが増加する","",""],
[165,"Passive<br><br>Increases T-ATK after Photon Flare has ended.","フォトンフレアの効果終了後、30秒間法撃力が上昇する","",""],
[166,"Passive<br><br>Increases the maximum duration of Shifta and Deband.","シフタ、デバンドの効果時間上限を延長する","",""],
[167,"Passive<br><br>Increases your S-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、打撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[168,"Passive<br><br>Increases your S-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、打撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[169,"Passive<br><br>Increases your R-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、射撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[170,"Passive<br><br>Increases your R-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、射撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[171,"Passive<br><br>Increases your T-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、法撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[172,"Passive<br><br>Increases your S-ATK and T-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、打撃力と法撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[173,"Passive<br><br>During Guard Stance, recover HP every time an enemy dies in your vicinity.","ガードスタンス中に一定範囲内でエネミーが死亡すると、HPが回復する","",""],
[174,"Active<br><br>Reduce damage taken and prevent flinching and being blown away.","ダメージを減少させ、さらに打ち上げや吹き飛ばしも防ぐ","",""],
[175,"Passive<br><br>Increases Shifta and Deband effect duration invoked on yourself.","自分が受けるシフタ・デバンド1回あたりの効果時間を増加する","",""],
[176,"Passive<br><br>When suffering under a status abnormality, increases your normal PP regeneration as well as PP regenerated by attacks.","自分が状態異常の間、PP自動回復量と攻撃によるPP回復量が上昇する","",""],
[177,"Passive<br><br>When suffering under a status abnormality, increases your attack.","自分が状態異常の間、打撃力が上昇する","",""],
[178,"Passive<br><br>Decreases PP consumption of PAs and techniques while a special bullet is loaded.","特殊弾を装填している間、PAとテクニックのPP消費量が減少する","",""],
[179,"Passive<br><br>Regenerates PP when inflicting damage to enemies with traps.","トラップでエネミーにダメージを与えると、PPが回復する","",""],
[180,"Passive<br><br>Increases your R-ATK for a fixed duration when you load a special bullet.","特殊弾を装填した際に、一定時間射撃力が上昇する","",""],
[181,"Passive<br><br>Increases damage inflicted to enemies during Stylish Roll.","スタイリッシュロール中、エネミーへのダメージが上昇する","",""],
[182,"Passive<br><br>Just Attacks after Stylish Roll gain a power bonus.","スタイリッシュロールからのジャストアタックに威力ボーナスを得る","",""],
[183,"Passive<br><br>Pressing the PA button during Stylish Roll consumes PP and makes you perform a powerful attack.","スタイリッシュロール中にPAボタンで攻撃を行うことにより、PPを消費して威力の高い攻撃を行う","",""],
[184,"Passive<br><br>Increases your maximum PP when equipped with twin machine guns during Showtime.","ショウタイム中、ツインマシンガン装備時にPP最大値が上昇する","",""],
[185,"Passive<br><br>Increases the chance to inflict status abnormalities while Photon Flare is in effect.","フォトンフレア発動時に、状態異常を与える確率が上昇する","",""],
[186,"Passive<br><br>Increases the duration of freeze status and makes it more difficult to break it by attacking.","状態異常フリーズの耐久力が上昇し、攻撃によって解除されにくくなる","",""],
[187,"Passive<br><br>Increases the area of effect and power of Freeze Ignition.","フリーズイグニッションの効果範囲と威力が上昇する","",""],
[188,"Passive<br><br>Adds S-ATK by a certain ratio depending on the T-ATK of your equipped wand.","装備しているウォンドの法撃力から一定割合を打撃力として追加する","",""],
[189,"Active<br><br>Gain a bonus to Wand Gear and S-ATK and enable the use of a quick Step attack. Only takes effect if Wand Gear is learnt.<br><i>Note: this skill actually gives you a bonus to striking damage, not S-ATK.</i>","ウォンドギアと打撃力にボーナスを得て、素早いステップ攻撃が可能になる。ウォンドギア習得時のみ有効","",""],
[190,"Active<br><br>Katana-exclusive skill that allows for high-speed movement and attacks to nearby enemies. Activate the skill again for a finishing strike.","一定時間、近くのエネミーに対して高速の移動と斬撃を繰り出せるようになる。再度スキルボタンを押すことで止めの一撃","",""],
[191,"Passive<br><br>Grants a damage bonus to striking attacks performed as Just Attacks during Katana Combat.","カタナコンバット中、打撃攻撃のジャストアタックにダメージボーナスを得る","",""],
[192,"Passive<br><br>Grants a damage bonus to Katana Combat Finish.","カタナコンバットフィニッシュにダメージボーナスを得る","",""],
[193,"Active<br><br>Sacrifice the power of your bullet bow's basic attacks to fire up to 3 shots rapidly.","一定時間、バレットボウの通常攻撃威力と攻撃間隔を犠牲にすることで、段階的に最大で3連射まで射撃が行える効果を得る","",""],
[194,"Passive<br><br>When equipped with a bullet bow increase your R-ATK during Rapid Shoot.","ラピッドシュート中、バレットボウ装備時に射撃力が上昇する","",""],
[195,"Passive<br><br>When equipped with a bullet bow gain a damage bonus during Rapid Shoot.","ラピッドシュート中、バレットボウ装備時にダメージボーナスを得る","",""],
[196,"Active<br><br>Stance which grants an unconditional damage bonus.","無条件にダメージボーナスを得るスタンススキル","",""],
[197,"Passive<br><br>Grants a damage bonus during Average Stance.","アベレージスタンス中の攻撃にダメージボーナスを得る","",""],
[198,"Passive<br><br>Increases your critical hit rate during Average Stance.","アベレージスタンス中クリティカルヒット確率が上昇する","",""],
[199,"Passive<br><br>Increases damage of charged attacks during Average Stance.","アベレージスタンス中チャージ攻撃のダメージが上昇する","",""],
[200,"Active<br><br>Stance which increases damage when attacking weak points and casting techniques of weak element. Decreases damage to non-weak points.","弱点部位を攻撃した時のダメージと、法撃による弱点属性へのダメージが増加するスタンススキル。弱点以外へのダメージは減少。リキャスト60秒","",""],
[201,"Passive<br><br>Grants a damage bonus to attacks that are affected by Weak Stance.","ウィークスタンスで有効となる攻撃にダメージボーナスを得る","",""],
[202,"Passive<br><br>Increases the critical hit rate of attacks that are affected by Weak Stance.","ウィークスタンスで有効となる攻撃のクリティカルヒット確率が上昇する","",""],
[203,"Passive<br><br>Grants a damage bonus to charged attacks that are affected by Weak Stance.","ウィークスタンスで有効となるチャージ攻撃にダメージボーナスを得る","",""],
[204,"Passive<br><br>Adds S-ATK and R-ATK by a fixed rate depending on the APT of your equipped Mag.","装備しているマグの技量から一定割合を打撃力と射撃力に加える","",""],
[205,"Passive<br><br>Increases your APT when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ☆10以上の武器を装備していると、技量が上昇する。このスキルはメインクラスのみ適用される","",""],
[206,"Passive<br><br>Recover HP whenever you use Just Reversal.","ジャストリバーサル発動時に、HPが回復するようになる","",""],
[207,"Passive<br><br>Deal striking damage during Step.","ステップで打撃ダメージを与えられるようになる","",""],
[208,"Passive<br><br>Increases your S-ATK for 60 seconds after Iron Will activates. Become invulnerable for a short time. Higher levels increase S-ATK and invulnerability duration.","アイアンウィル発動後、60秒間打撃力が増加し、短時間無敵状態になる。レベルが上がると打撃力と無敵時間が増加する。","",""],
[209,"Passive<br><br>Shortens the duration of status abnormalities inflicted on you.","自分が受けた状態異常の時間を短縮する","",""],
[210,"Passive<br><br>Increases your chance to inflict a status abnormality when your HP are below 50%.","HPが50%未満になったとき、状態異常の付与確率が上昇する","",""],
[211,"Passive<br><br>Gain a damage bonus when attacking an enemy suffering under a status abnormality.","状態異常を受けているエネミーに対して攻撃を行うとダメージボーナスを得る","",""],
[212,"Passive<br><br>Gain a bonus to your PB growth rate when attacking a weak spot with shooting attacks.","射撃で弱点部位を攻撃したときのPBゲージ増加量にボーナスを得る","",""],
[213,"Passive<br><br>Gain a damage bonus when attacking an enemy with full HP.","HPが減っていないエネミーに対して攻撃を行うとダメージボーナスを得る","",""],
[214,"Passive<br><br>Increases critical rate when hitting with shooting attacks at close range.","近距離で射撃攻撃をヒットするとクリティカル率が上昇する","",""],
[215,"Passive<br><br>Decreases Gear reduction rate from taken damage during Showtime. Only takes effect if Twin Machine Gun Gear is learnt.","ショウタイム中、被ダメージによるギア減少量を軽減する。ツインマシンガンギア習得時のみ有効","",""],
[216,"Passive<br><br>Gain a power bonus to techniques invoked from a thrown Talis.","投げたタリスから発動するテクニックに威力ボーナスを得る","",""],
[217,"Passive<br><br>Increases T-ATK. More efficient than Technique Up.","法撃力が上昇する。法撃アップより効果が高い","",""],
[218,"Passive<br><br>Recover your own and your target's HP whenever a status abnormality is cured. PP recovery rate is also increased for a fixed time.","状態異常を回復した際、自分と対象者のHPを回復させ、一定時間PP回復量も上昇させる","",""],
[219,"Passive<br><br>Reduces the PP consumption of support techniques during Territory Burst. Only takes effect if Territory Burst is learnt.","テリトリーバースト中、補助テクニックの消費PPを軽減する。テリトリーバースト習得時のみ有効","",""],
[220,"Passive<br><br>Gain invulnerability at the start of Katana Combat. Only takes effect for your main class.","カタナコンバット開始時に無敵時間が発生する。このスキルはメインクラスのみ適用される","",""],
[221,"Passive<br><br>When equipped with a bullet bow increase your R-ATK during Rapid Shoot.","ラピッドシュート中、バレットボウ装備時に射撃力が上昇する","",""],
[222,"Passive<br><br>During Fury Stance and Guard Stance, gain a bonus to the gear gauge increase rate for Hunter weapons. Only takes effect for your main class.","フューリースタンス時、ハンター武器のギアゲージの上昇率にボーナスを得る。このスキルはメインクラスのみ適用される","",""],
[223,"Passive<br><br>Increase your critical hit rate and gain a damage bonus to criticals. Only takes effect for your main class.","クリティカルヒット確率が上昇し、クリティカル時にダメージボーナスを得る。このスキルはメインクラスのみ適用される","",""],
[224,"Passive<br><br>Increase damage when hitting from long range. Only takes effect for your main class.","遠距離で攻撃をヒットするとダメージが上昇する。このスキルはメインクラスのみ適用される","",""],
[225,"Passive<br><br>During Showtime, gradually get a power bonus. The power bonus is reset if you receive damage. Only takes effect for your main class.","ショウタイム中、徐々に威力ボーナスが増加していく。ダメージを受けると威力ボーナスはリセットされる。このスキルはメインクラスのみ適用される","",""],
[226,"Passive<br><br>Your weapon's attribute value is transformed into a damage bonus for techniques. When the attributes are identical, the effect is maximized. Only takes effect for your main class.","武器の属性値をテクニックのダメージボーナスに変換する。属性が一致すると最大値となる。このスキルはメインクラスのみ適用される。","",""],
[227,"Passive<br><br>Increase the effect duration of Shifta and Deband per tick. Only takes effect for your main class.","シフタ、デバンド一回あたりの効果時間を増加する。このスキルはメインクラスのみ適用される","",""],
[228,"Passive<br><br>If you counter, an additional enemy piercing slash is released.","カウンターの際に、敵を貫通する追加の斬撃を放つ","",""],
[229,"Passive<br><br>Reduce Rapid Shoot's cooldown and increase the amount of PP recovered with normal attacks during Rapid Shoot.","ラピッドシュートのリキャストを軽減し、ラピッドシュート中の通常攻撃によるPP回復量が上昇する","",""],
[230,"Passive<br><br>When performing a Just Guard, recover HP to yourself and players around you.","ジャストガード発動時、自分と周囲にいるキャラクターのHPを回復する","",""],
[231,"Passive<br><br>When using War Cry, recover PP according to the number of enemies affected and gain a damage bonus for 30 seconds. Only takes effect for your main class.","ウォークライ発動時、対象エネミー数に応じてPPが回復し、30秒ダメージボーナスを得る。このスキルはメインクラスのみ適用される","",""],
[232,"Passive<br><br>Gain a damage bonus when using different PAs or Techniques in succession with Just Attacks.","異なるPAやテクニックを連続でジャストアタックするとダメージボーナスを得る","",""],
[233,"Active<br><br>Reduce your maximum HP and temporarily gain a damage bonus for striking attacks. Only takes effect for your main class.","一時的に打撃威力にダメージボーナスを得るが、最大HPが減少する。このスキルはメインクラスのみ適用される","",""],
[234,"Active<br><br>Throw a bomb that sucks in enemies in an area.","周囲のエネミーを吸い寄せる特殊な爆弾を投擲する","",""],
[235,"Passive<br><br>When loading special bullets, the bullets do not disappear when switching to assault rifles or launchers. Only takes effect for your main class.","特殊弾を装填した時、アサルトライフル、ランチャーに切り替えても弾が消えなくなる。このスキルはメインクラスのみ適用される","",""],
[236,"Passive<br><br>When equipped with twin machine guns, double the accumulated chain count from attacks.","ツインマシンガン装備時、攻撃で溜まるチェイン数が倍になる","",""],
[237,"Passive<br><br>When using Chain Finish, reduce the cooldown of Chain Trigger according to the accumulated chain count.","チェインフィニッシュ発動時、チェイン数に応じてチェイントリガーのリキャスト時間が軽減される","",""],
[238,"Passive<br><br>When performing a recovery action during a technique charge, the state of the charge is temporarily kept. Only takes effect for your main class.","テクニックチャージ中に回避アクションを使用すると、一時的にチャージ中の状態をキープする。このスキルはメインクラスのみ適用される","",""],
[239,"Passive<br><br>Increase the damage dealt to enemies during Shifta. Only takes effect for your main class.","シフタ効果中にエネミーへのダメージが増加する。このスキルはメインクラスのみ適用される","",""],
[240,"Passive<br><br>Increase the maximum HP during Deband. Only takes effect for your main class.","デバンド効果中に最大HPが上昇する。このスキルはメインクラスのみ適用される。","",""],
[241,"Passive<br><br>Increase the power of normal attacks.","通常攻撃の威力が上昇する。","",""],
[242,"Passive<br><br>Increase the power of charged normal attacks and bullet velocity when equipped with a bullet bow.","バレットボウ装備時、チャージ通常攻撃の威力と弾速が上昇する","",""],
[243,"Passive<br><br>Recover PP when using Just Reversal.","ジャストリバーサル発動時に、PPが回復するようになる","",""],
[244,"Passive<br><br>Increases your S-ATK and T-ATK when equipping a \u260510 or rarer weapon. Only takes effect for your main class.","レアリティ★10以上の武器を装備していると、打撃力と法撃力が上昇する。このスキルはメインクラスのみ適用される","",""],
[245,"Passive<br><br>Gain a bonus to your equipment's status when equipping crafted weapons or armour.","クラフト武器や防具を装備すると装備のステータスにボーナスを得る","",""],
[246,"Passive<br><br>Adds S-ATK and T-ATK by a fixed rate depending on the APT of your equipped Mag.","装備しているマグの技量から一定割合を打撃力と法撃力に加える","",""],
[247,"Passive<br><br>Charge gear whenever you attack or charge a technique. Increase the power your attacks and change your weapon's attribute to the one of your last charged technique.","攻撃を当てるかテクニックをチャージするとギアが溜まる。武器の属性が最後にチャージしたテクニックと同じ属性になり、攻撃の威力が上昇する","",""],
[248,"Passive<br><br>Charge gear whenever you attack. Using your weapon action will hurl photon blades towards your enemy and consume gear. Attacking pinned parts will increase your PP recovery.","攻撃を当てるとギアが溜まり、武器アクションでギアを消費して敵にフォトンブレードを飛ばす。刺さった部位に対しての攻撃はPP回復量が上昇する","",""],
[249,"Active<br><br>Create a field around yourself that increases the amount of PP recovered by attacks using an enemy's attribute weakness.","自分の周囲に、エネミーの弱点属性で攻撃を当てた場合PP回復量が上昇するフィールドを発生させる","",""],
[250,"Active<br><br>Create a field around yourself that increases critical rate.","自分の周囲にクリティカル率が上昇するフィールドを発生させる","",""],
[251,"Passive<br><br>Gain a damage bonus to mid-air attacks during Shifta.","シフタ効果中、空中での攻撃にダメージボーナスを得る","",""],
[252,"Passive<br><br>Increase the amount of PP recovered by normal attacks during Deband.","デバンド効果中、通常攻撃によるPP回復量が上昇する","",""],
[253,"Passive<br><br>When recovering HP, heal surrounding players by a fixed percentage of the original healing.","HPを回復した際、回復した値の一定割合分、周囲のキャラクターを回復する","",""],
[254,"Passive<br><br>When recovering HP, gain a bonus to the recovered amount.","HPを回復する際に回復量にボーナスを得る","",""],
[255,"Active<br><br>During the effect duration, increase the speed of jet boots attacks as well as the charge speed of PAs and Techniques.","効果時間中、ジェットブーツの攻撃速度とテクニック・PAのチャージ速度上昇","",""],
[256,"Passive<br><br>Just Attacks during Rapid Burst gain a power bonus.","ラピッドブースト中のジャストアタックに威力ボーナス","",""],
[257,"Passive<br><br>When the attribute obtained by the gear is released with your weapon action, cause an attribute explosion that has a fixed chance to apply a status abnormality. Only takes effect if Jet Boots Gear is learnt.","ギアに保存された属性を武器アクションで破棄した時、属性爆発を発生させ、一定確率で状態異常が発動する。ジェットブーツギア習得時のみ有効","",""],
[258,"Passive<br><br>Jet boots exclusive skill. Change jet boots attacks so that they are influenced by your S-ATK. Only takes effect for your main class.","ジェットブーツ専用スキル　ジェットブーツによる攻撃を打撃力によって行うように切り替える。このスキルはメインクラスのみ有効","",""],
[259,"Active<br><br>During the effect duration, double the amount of fired photon blades.","効果時間中、フォトンブレードの発射数が倍になる","",""],
[260,"Passive<br><br>Increase the power of photon blades during Photon Blade Fever.","フォトンブレードフィーバー中、フォトンブレードの威力がアップする","",""],
[261,"Passive<br><br>Gain invulnerability to the movement after photon blade usage.","フォトンブレード使用時の移動に無敵時間が発生する","",""],
[262,"Active<br><br>Stance which increases the damage when attacking an enemy with a weapon of its attribute weakness and casting techniques of weak element.","エネミー弱点属性武器で攻撃した時と、法撃で弱点属性へ攻撃したときのダメージが増加するスタンススキル","",""],
[263,"Passive<br><br>During Elemental Stance, gain a damage bonus when attacking an enemy with a weapon of its attribute weakness.","エレメンタルスタンス中、エネミーの弱点属性武器で攻撃した際にダメージボーナスを得る","",""],
[264,"Passive<br><br>During Elemental Stance, increase your critical hit rate when attacking an enemy with a weapon of its attribute weakness.","エレメンタルスタンス中、エネミーの弱点属性武器で攻撃した際にクリティカルヒット確率が上昇する。","",""],
[265,"Active<br><br>Stance which increases damage when attacking breakable parts.","部位破壊可能箇所へのダメージが増加するスタンススキル","",""],
[266,"Passive<br><br>During Break Stance, gain a damage bonus when attacking breakable parts.","ブレイクスタンス中、部位破壊可能箇所へ攻撃した際にダメージボーナスを得る","",""],
[267,"Passive<br><br>During Break Stance, increase your critical hit rate when attacking breakable parts.","ブレイクスタンス中、部位破壊可能箇所へ攻撃した際にクリティカルヒット確率が上昇する","",""],
[268,"Passive<br><br>Increase your APT.","技量が上昇する","",""],
[269,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[270,"Passive<br><br>Increase your S-ATK.","打撃力が上昇する","",""],
[271,"Passive<br><br>Increase your T-ATK.","法撃力が上昇する","",""],
[272,"Passive<br><br>Increase your S-DEF.","打撃防御力が上昇する","",""],
[273,"Passive<br><br>Increase your T-DEF.","法撃防御力が上昇する","",""],
[274,"Passive<br><br>Allows guarding from all directions with Hunter weapons only. Only takes effect for your main class.","ハンター武器のみ全方向にガードが可能になる。このスキルはメインクラスのみ適用される","",""],
[275,"Passive<br><br>Gain a damage bonus for a fixed period of time after successfully performing Just Guard during Guard Stance. Only takes effect for your main class.","ガードスタンス時にジャストガードを成功させると、一定時間ダメージボーナスを得る。このスキルはメインクラスのみ適用される","",""],
[276,"Passive<br><br>Just Guard becomes possible at the beginning of the weapon action of double sabers.","ダブルセイバーでかまいたちを発生させた瞬間にジャストガードが可能になる","",""],
[277,"Passive<br><br>Movement in every direction becomes possible during the twin dagger spin.","ツインダガーのスピン中に任意の方向に移動が可能になる","",""],
[278,"Passive<br><br>Increases knuckle gear generation at double its normal speed.","ナックルギアが通常の倍、増加するようになる","",""],
[279,"Passive<br><br>Allows attack actions during Dive Roll.","ダイブロール中の攻撃アクションが可能となる","",""],
[280,"Passive<br><br>Increases the damage of shooting attacks while moving.","移動した状態で射撃したときのダメージが上昇する","",""],
[281,"Passive<br><br>Allows attack actions during Dive Roll.","ダイブロール中の攻撃アクションが可能となる","",""],
[282,"Passive<br><br>Reactivates Show Time again once if no damage was received during Show Time.","ショウタイム効果終了時までダメージを受けなかった場合、一度だけショウタイムが再発動する","",""],
[283,"Passive<br><br>When equipped with a rod, the technique kept with Charge Escape can be used without PP consumption.","ロッド装備時、PPを消費せずにチャージエスケープでキープしたテクニックを使用出来る","",""],
[284,"Passive<br><br>Apply your Shifta and Deband to revived allies.","復活させた味方に自分が習得しているシフタとデバンドが付与される","",""],
[285,"Active<br><br>Create a field that revives allies around you. Only takes effect for your main class.","周囲の味方を復活させるフィールドを展開する。このスキルはメインクラスのみ適用される","",""],
[286,"Passive<br><br>Creates a Just Attack circle during Snatch Step.","スナッチステップ中に、ジャストアタックタイミングが発生するようになる","",""],
[287,"Passive<br><br>Allows faster usage of mate items.","メイト系アイテムが素早く使用出来る","",""],
[288,"Passive<br><br>Maintains the effect of fields for a fixed period of time for players that have left your field.","習得者が使用するフィールドの効果範囲外に出ても、一定時間フィールド効果が維持される","",""],
[289,"Passive<br><br>When equipped with D Blades, the effect of Break Stance also takes effect on non-breakable parts. Only takes effect for your main class.","Dブレード装備時、スキル「ブレイクスタンス」の効果のみが破壊可能箇所以外にも有効になる。このスキルはメインクラスのみ適用される","",""],
[290,"Passive<br><br>Recover PP after successfully performing a Just Guard with a Hunter weapon. Only takes effect for your main class.","ハンター武器でジャストガードを成功させるとPPが回復する。このスキルはメインクラスのみ適用される","",""],
[291,"Passive<br><br>Recover all PP after Limit Break ends. Only takes effect for your main class.","リミットブレイク終了時にPPが全回復する。このスキルはメインクラスのみ適用される","",""],
[292,"Passive<br><br>Prevent flinching and being blown away while loading a special bullet. Only takes effect for your main class.","特殊弾を装填する時、打ち上げや吹き飛ばしを防ぐ。このスキルはメインクラスのみ適用される","",""],
[293,"Passive<br><br>Increase PP recovery rate and gain a damage bonus to critical hits when equipped with twin machine guns. Only takes effect for your main class.","ツインマシンガン装備時、PP回復量が増加し、クリティカル時にダメージボーナスを得る。このスキルはメインクラスのみ適用される","",""],
[294,"Active<br><br>Increases your talis throw speed. Only takes effect for your main class.","タリスの速度が上昇する。このスキルはメインクラスのみ適用される","",""],
[295,"Passive<br><br>Increase the area of effect for Resta, Anti, Shifta and Deband. Only takes effect for your main class.","「レスタ」「アンティ」「シフタ」「デバンド」の効果範囲が上昇する。このスキルはメインクラスのみ適用される","",""],
[296,"Passive<br><br>Countering and Counter Edge gain a damage bonus and recover PP. Only takes effect for your main class.","カウンターとカウンターエッジでPPが回復し、威力ボーナスを得る。このスキルはメインクラスのみ適用される","",""],
[297,"Passive<br><br>Decrease PP consumption and charge time for charge PAs when equipped with a bullet bow. Only takes effect for your main class.","バレットボウ装備時、チャージPAのチャージ時間とPP消費量を軽減する。このスキルはメインクラスのみ適用される","",""],
[298,"Passive<br><br>Gain invulnerability during PA follow-ups when equipped with jet boots. Only takes effect for your main class.","ジェットブーツ装備時、PAの派生を行った時に無敵時間が発生する。このスキルはメインクラスのみ適用される","",""],
[299,"Passive<br><br>Increase the gear gauge increase rate for attacks while under the effect of Shifta or Deband when equipped with jet boots. Only takes effect for your main class.","ジェットブーツ装備時、シフタ及はデバンド効果中、攻撃によるギア増加量が上昇する。このスキルはメインクラスのみ適用される","",""]
]

descheadertrans = [
[  0,"Level","レベル","",""],
[  1,"Maximum HP","HP最大値","",""],
[  2,"Maximum PP","PP最大値","",""],
[  3,"S-ATK","打撃力","",""],
[  4,"R-ATK","射撃力","",""],
[  5,"T-ATK","法撃力","",""],
[  6,"APT","技量","",""],
[  7,"S-DEF","打撃防御","",""],
[  8,"R-DEF","射撃防御","",""],
[  9,"T-DEF","法撃防御","",""],
[ 10,"Striking Power","打撃威力","",""],
[ 11,"Shooting Power","射撃威力","",""],
[ 12,"Received Striking Damage","被打撃ダメージ","",""],
[ 13,"Duration","効果時間","",""],
[ 14,"Cooldown","リキャスト","",""],
[ 15,"Power","威力","",""],
[ 16,"Proc Rate","発動率","",""],
[ 17,"HP Recovery Rate","HP回復率","",""],
[ 18,"Received Damage","被ダメージ","",""],
[ 19,"Hate","ヘイト効果","",""],
[ 20,"Reduction Rate","軽減率","",""],
[ 21,"Invulnerability Duration","無敵時間","",""],
[ 22,"Status Abnormality Duration","状態異常時間","",""],
[ 23,"Frontal Power","正面威力","",""], //FI
[ 24,"Back Power","背面威力","",""],
[ 25,"PP Increase Rate","PP増加率","",""],
[ 26,"PP Recovery Rate","PP回復率","",""], //RA
[ 27,"Charges","装填数","",""],
[ 28,"PP Consumption Rate","PP消費率","",""],
[ 29,"PB Gauge Increase Rate","PBゲージ増加率","",""],
[ 30,"PP Recovery Amount","PP回復量","",""],
[ 31,"Gear Growth Rate","ギア上昇率","",""], //GU
[ 32,"Power Increase per Second","秒間威力上昇量","",""],
[ 33,"Maximum Power Increase","威力上昇量上限","",""],
[ 34,"Gear Reduction Rate","ギア減少量","",""],
[ 35,"PP Consumption","PP消費量","",""],
[ 36,"All Resist","全体耐性","",""],
[ 37,"Same Attribute Conversion Rate","同属性変換率","",""],
[ 38,"Different Attribute Conversion Rate","他属性変換率","",""],
[ 39,"Status Abnormality Chance","状態異常確率","",""],
[ 40,"Reduction Rate","減少率","",""],
[ 41,"Freeze Durability","フリーズ耐久力","",""],
[ 42,"Conversion Rate","変換率","",""],
[ 43,"Shifta Effect","シフタ効果","",""],
[ 44,"Deband Effect","デバンド効果","",""],
[ 45,"HP Recovery","HP回復量","",""],
[ 46,"Weakness Striking Power","弱点打撃威力","",""],
[ 47,"Weakness Shooting Power","弱点射撃威力","",""],
[ 48,"Weakness Technique Power","弱点法撃威力","",""],
[ 49,"Non-weakness Power","弱点以外威力","",""],
[ 50,"Attack Interval","攻撃間隔","",""],
[ 51,"Cooldown Reduction","リキャスト軽減率","",""],
[ 52,"S-ATK Conversion Rate","打撃力変換率","",""],
[ 53,"R-ATK Conversion Rate","射撃力変換率","",""],
[ 54,"Power Increase Rate","威力上昇率","",""],
[ 55,"Technique Power","法撃威力","",""],
[ 56,"PP Consumption","消費PP","",""],
[ 57,"Maximum PP Recovery Amount","PP回復量上限","",""],
[ 58,"Velocity","弾速","",""],
[ 59,"T-ATK Conversion Rate","法撃力変換率","",""],
[ 60,"Craft Bonus","クラフトボーナス","",""],
[ 61,"Occurrence Duration","発生時間","",""],
[ 62,"HP Recovery Improvement","HP回復量補正","",""],
[ 63,"Attack Speed","攻撃速度","",""],
[ 64,"Charge Reduction","チャージ軽減","",""],
[ 65,"Weakness Weapon Power","弱点武器威力","",""],
[ 66,"Non-Weakness Weapon Power","非弱点武器威力","",""],
[ 67,"Unbroken Part Power","未破壊部位威力","",""],
[ 68,"Non-Breakable Part Power","非破壊部位威力","",""],
[ 69,"Effectiveness","有効割合","",""],
[ 70,"Critical Hit Power","クリティカル威力","",""],
[ 71,"Edge Power","エッジ威力","",""],
[ 72,"Edge PP Recovery Amount","エッジPP回復量","",""],
[ 73,"Charge Time","チャージ時間","",""]
]